name: dist-stat-tutorial
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - pip
  - pytorch-cpu=1.1
  - torchvision-cpu
#  - opencv
#  - matplotlib
  - jupyterlab
#  - librosa
  - nb_conda_kernels
#  - pip:
#    - torchtext
#    - torchviz
