name: dist-stat-tutorial
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - pip
  - pytorch=1.4
  - torchvision
  - cpuonly
#  - opencv
#  - matplotlib
  - jupyterlab
#  - librosa
  - nb_conda_kernels
#  - pip:
#    - torchtext
#    - torchviz
