#!/bin/sh
#$ -cwd
#$ -N cox-real
#$ -pe mpi 40
#$ -j y
date
module load mpi/openmpi-x86_64
source /shared/conda/etc/profile.d/conda.sh
export PATH=/shared/conda/bin:$PATH
export LD_LIBRARY_PATH=/shared/conda/lib:$LD_LIBRARY_PATH
export MKL_NUM_THREADS=18
mpirun -np 40 python /shared/dist_stat/examples/test_cox_breslow_realdata_200k.py --double --step=10 --tol=1e-6 --nosubnormal --iter=5000 --lambda=$1 --out-prefix=run_200k_${JOB_ID} --datnormest=212722.1829
